[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Matti Astrand <mattiastr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "8"
ndarray = "0.17"
structopt = "0.3"
color-eyre = "0.6"
